# Generated by Django 3.1.2 on 2021-02-01 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosapp', '0004_auto_20210127_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosdelresponsable',
            name='usuario_fore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serviciosapp.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datospersonadequiendepende',
            name='usuario_fore',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='serviciosapp.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='usuario_fore',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='serviciosapp.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gastofamiliarmensual',
            name='usuario_fore',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='serviciosapp.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gastosdelsolicitante',
            name='usuario_fore',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='serviciosapp.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacionsocioeconomica',
            name='usuario_fore',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='serviciosapp.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresofamiliarmensual',
            name='usuario_fore',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='serviciosapp.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediosparaestudiar',
            name='usuario_fore',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='serviciosapp.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personasquedependendelingresomensual',
            name='usuario_fore',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='serviciosapp.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gastosdelsolicitante',
            name='celular',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='gastosdelsolicitante',
            name='jefe_de_familia',
            field=models.CharField(max_length=3),
        ),
    ]
