# Generated by Django 3.1.2 on 2021-02-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosapp', '0008_datospersonales_usuario_fore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonales',
            name='usuario_fore',
        ),
    ]
