# Generated by Django 3.1.2 on 2021-02-02 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosapp', '0012_datospersonales_usuario_fore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datospersonales',
            old_name='usuario_fore',
            new_name='usuario_foraneo',
        ),
    ]
