# Generated by Django 3.1.2 on 2021-02-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosapp', '0013_auto_20210202_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonales',
            name='usuario_foraneo',
        ),
    ]
