# Generated by Django 3.1.2 on 2021-02-02 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosapp', '0014_remove_datospersonales_usuario_foraneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='usuario_foraneo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='serviciosapp.usuario'),
            preserve_default=False,
        ),
    ]
