# Generated by Django 3.1.2 on 2021-02-02 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosapp', '0017_delete_datospersonalesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='datosPersonalesC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('solicita_beca_alimentaria', models.CharField(max_length=3)),
                ('ap_paterno', models.CharField(max_length=30)),
                ('ap_materno', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=3)),
                ('edad', models.IntegerField(default=0)),
                ('estado_civil', models.CharField(max_length=30)),
                ('carrera', models.CharField(max_length=30)),
                ('semestre', models.IntegerField(default=0)),
                ('grupo', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('otro_idiona', models.CharField(max_length=30)),
                ('residencia_distinta', models.CharField(max_length=3)),
                ('calle', models.CharField(max_length=30)),
                ('numero', models.IntegerField(default=0)),
                ('colonia', models.CharField(max_length=30)),
                ('municipio', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('propietario', models.CharField(max_length=30)),
                ('parentesco', models.CharField(max_length=30)),
                ('usuario_foraneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosapp.usuario')),
            ],
        ),
    ]
