# Generated by Django 3.1.2 on 2021-02-02 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosapp', '0018_datospersonalesc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='datosPersonaDeQuienDepende',
        ),
    ]
