# Generated by Django 3.1.2 on 2021-02-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosapp', '0019_delete_datospersonadequiendepende'),
    ]

    operations = [
        migrations.CreateModel(
            name='datosPersonaDeQuienDepende',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_paterno', models.CharField(max_length=30)),
                ('ap_materno', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=30)),
                ('edad', models.IntegerField(default=0)),
                ('estado_civil', models.CharField(max_length=30)),
                ('telefono_fijo', models.CharField(max_length=30)),
                ('celular', models.CharField(max_length=30)),
                ('parentesco', models.CharField(max_length=30)),
                ('calle', models.CharField(max_length=60)),
                ('numero', models.IntegerField(default=0)),
                ('colonia', models.CharField(max_length=30)),
                ('municipio', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('grado_escolaridad', models.CharField(max_length=30)),
                ('tipo_de_trabajo', models.CharField(max_length=30)),
                ('ocupacion', models.CharField(max_length=60)),
                ('texto_ocupacion', models.CharField(max_length=60)),
                ('empresa', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('antiguedad', models.CharField(max_length=30)),
                ('telefono_empresa', models.CharField(max_length=30)),
                ('calle_empresa', models.CharField(max_length=30)),
                ('numero_empresa', models.CharField(max_length=30)),
                ('colonia_empresa', models.CharField(max_length=30)),
                ('municipio_empresa', models.CharField(max_length=30)),
                ('region_empresa', models.CharField(max_length=30)),
                ('estado_empresa', models.CharField(max_length=30)),
                ('ap_paterno_tercero', models.CharField(max_length=30)),
                ('ap_materno_tercero', models.CharField(max_length=30)),
                ('nombre_tercero', models.CharField(max_length=30)),
                ('edad_tercero', models.IntegerField(default=0)),
                ('parentesco_tercero', models.CharField(max_length=30)),
                ('telefono_tercero', models.CharField(max_length=30)),
                ('celular_tercero', models.CharField(max_length=30)),
                ('ocupacion_tercero', models.CharField(max_length=30)),
            ],
        ),
    ]
