# Generated by Django 3.1.2 on 2021-02-02 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosapp', '0020_datospersonadequiendepende'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='datosPersonalesC',
            new_name='datosPersonales',
        ),
    ]
