# Generated by Django 3.1.2 on 2021-02-02 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosapp', '0022_auto_20210202_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastosdelsolicitante',
            old_name='usuario_fore',
            new_name='usuario_foraneo',
        ),
    ]
