# Generated by Django 3.1.2 on 2021-02-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosapp', '0027_auto_20210203_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastofamiliarmensual',
            old_name='usuario_fore',
            new_name='usuario_foraneo',
        ),
    ]
