# Generated by Django 3.1.2 on 2021-02-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosapp', '0028_auto_20210203_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediosparaestudiar',
            name='falta_algun_medio',
            field=models.CharField(max_length=100),
        ),
    ]
