# Generated by Django 3.1.2 on 2021-02-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosapp', '0029_auto_20210203_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonadequiendepende',
            name='responsable_misma_persona',
            field=models.CharField(default='Si', max_length=10),
            preserve_default=False,
        ),
    ]
