# Generated by Django 3.1.2 on 2021-02-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosapp', '0030_datospersonadequiendepende_responsable_misma_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosdelresponsable',
            name='dependencia_jubilo',
        ),
        migrations.RemoveField(
            model_name='datosdelresponsable',
            name='jubilado',
        ),
        migrations.RemoveField(
            model_name='datosdelresponsable',
            name='labores_del_campo',
        ),
        migrations.RemoveField(
            model_name='datosdelresponsable',
            name='negocio_propio',
        ),
        migrations.RemoveField(
            model_name='datosdelresponsable',
            name='tipo_de_producto',
        ),
        migrations.AddField(
            model_name='datosdelresponsable',
            name='texto_ocupacion',
            field=models.CharField(default='lo que sea', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datosdelresponsable',
            name='ocupacion',
            field=models.CharField(max_length=100),
        ),
    ]
