# Generated by Django 3.1.2 on 2021-02-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosapp', '0034_auto_20210205_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaDependiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.CharField(max_length=30)),
                ('parentesco', models.CharField(max_length=30)),
                ('tipo_comprobante', models.CharField(max_length=30)),
                ('observaciones', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='personasquedependendelingresomensual',
            name='edades_personas',
        ),
        migrations.RemoveField(
            model_name='personasquedependendelingresomensual',
            name='nombres_personas',
        ),
        migrations.RemoveField(
            model_name='personasquedependendelingresomensual',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='personasquedependendelingresomensual',
            name='parentescos_personas',
        ),
        migrations.RemoveField(
            model_name='personasquedependendelingresomensual',
            name='tipo_comprobante_personas',
        ),
        migrations.AddField(
            model_name='personasquedependendelingresomensual',
            name='personas',
            field=models.ManyToManyField(to='serviciosapp.PersonaDependiente'),
        ),
    ]
