# Generated by Django 3.1.2 on 2021-02-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosapp', '0037_auto_20210213_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subirarchivos',
            name='media',
        ),
        migrations.RemoveField(
            model_name='subirarchivos',
            name='titulo',
        ),
        migrations.AddField(
            model_name='subirarchivos',
            name='comprobante_de_agua_luz_o_telefono',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subirarchivos',
            name='comprobante_de_depedientes',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subirarchivos',
            name='comprobante_de_ingresos',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subirarchivos',
            name='croquis',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subirarchivos',
            name='recibo_prospera',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
