# Generated by Django 3.1.2 on 2021-02-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosapp', '0038_auto_20210215_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subirarchivos',
            old_name='comprobante_de_agua_luz_o_telefono',
            new_name='comprobante_de_agua',
        ),
        migrations.RenameField(
            model_name='subirarchivos',
            old_name='croquis',
            new_name='comprobante_de_luz',
        ),
        migrations.RenameField(
            model_name='subirarchivos',
            old_name='recibo_prospera',
            new_name='comprobante_de_teléfono',
        ),
        migrations.AddField(
            model_name='subirarchivos',
            name='croquis_de_donde_habita_el_responsable',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subirarchivos',
            name='croquis_de_donde_habita_la_persona_de_quién_depende',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subirarchivos',
            name='croquis_de_donde_habita_solicitante',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subirarchivos',
            name='ultimo_recibo_prospera',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
